project_id = "vfcfkcpnrgdfgkvnyyvd"

[functions.generate-abaqus-script]
verify_jwt = false

[functions.debug-abaqus-script]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.prompt-builder]
verify_jwt = false
